TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.01
  max_vel_theta: 0.5
  min_vel_theta: -0.5
  min_in_place_rotational_vel: 0.1
  sin_granularity: 0.025
  angular_sin_granularity: 0.025
  pdist_scale: 0.6
  gdist_scale: 0.8
  accdist_scale: 0.01
  oscillation_reset_dist: 0.05
  escape_reset_dist: 0.1
  escape_reset_theta: 0.01
  vx_samples: 20
  max_rotational_vel: 0.3

  acc_lim_th: 1.0
  acc_lim_x: 0.2
  acc_lim_y: 2.5

  holonomic_robot: false
